name: "ESPN Bot"
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - run: npm ci
      - run: npm run build
      - name: Send post
        run: npm start
        env:
          BSKY_HANDLE: "espnbot.bsky.social"
          BSKY_PASSWORD: ${{ secrets.ESPN_BSKY_PASSWORD }}
          MASTODON_HANDLE: "@espn@sportsbots.xyz"
          MASTODON_ACCOUNT_ID: "109745093287034711"
          ALTERNATE_CARD_IMAGE: "https://pbs.twimg.com/profile_images/1170690523201527808/FriNRiir_400x400.png"
