name: "Liverpool FC Bot"
on:
  schedule:
    - cron: "*/12 0-7,14-23 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - run: npm ci
      - run: npm run build
      - name: Send post
        run: npm start
        env:
          BSKY_HANDLE: "lfcbot.bsky.social"
          BSKY_PASSWORD: ${{ secrets.LFC_BSKY_PASSWORD }}
          MASTODON_HANDLE: "@lfc@sportsbots.xyz"
          MASTODON_ACCOUNT_ID: "109787827684130095"
          ALTERNATE_CARD_IMAGE: "https://pbs.twimg.com/profile_images/1856268307868844032/lbdn4-vK_400x400.jpg"
